const employeesData = [
  {
    id: 1,
    name: "Johnson Wood",
    role: "Front End Developer",
    email: "johnsonwood@microsoft.com",
    status: "Active",
  },
  {
    id: 2,
    name: "John Doe",
    role: "Team Lead",
    email: "johndoe@microsoft.com",
    status: "Active",
  },
  {
    id: 3,
    name: "Fakhar Naveed",
    role: "UX/UI Designer",
    email: "fakhar@microsoft.com",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Alex Mode",
    role: "Software Engineer",
    email: "alexmode@microsoft.com",
    status: "Active",
  },
  {
    id: 5,
    name: "Emma Brown",
    role: "Data Scientist",
    email: "emmabrown@microsoft.com",
    status: "Active",
  },
  {
    id: 6,
    name: "Liam Davis",
    role: "Backend Developer",
    email: "liamdavis@microsoft.com",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Olivia Wilson",
    role: "Product Manager",
    email: "oliviawilson@microsoft.com",
    status: "Active",
  },
  {
    id: 8,
    name: "Noah Johnson",
    role: "DevOps Engineer",
    email: "noahjohnson@microsoft.com",
    status: "Active",
  },
  {
    id: 9,
    name: "Sophia Lee",
    role: "UI/UX Designer",
    email: "sophialee@microsoft.com",
    status: "Inactive",
  },
  {
    id: 10,
    name: "James White",
    role: "Cloud Architect",
    email: "jameswhite@microsoft.com",
    status: "Active",
  },
  {
    id: 11,
    name: "Isabella Moore",
    role: "Business Analyst",
    email: "isabellamoore@microsoft.com",
    status: "Active",
  },
  {
    id: 12,
    name: "Ethan Miller",
    role: "Software Tester",
    email: "ethanmiller@microsoft.com",
    status: "Inactive",
  },
  {
    id: 13,
    name: "Mia Taylor",
    role: "AI Engineer",
    email: "miataylor@microsoft.com",
    status: "Active",
  },
  {
    id: 14,
    name: "Benjamin Anderson",
    role: "Mobile Developer",
    email: "benjaminanderson@microsoft.com",
    status: "Inactive",
  },
  {
    id: 15,
    name: "Ava Martinez",
    role: "Scrum Master",
    email: "avamartinez@microsoft.com",
    status: "Active",
  },
  {
    id: 16,
    name: "Lucas Thomas",
    role: "Security Engineer",
    email: "lucasthomas@microsoft.com",
    status: "Active",
  },
  {
    id: 17,
    name: "Charlotte Harris",
    role: "Full Stack Developer",
    email: "charlotteharris@microsoft.com",
    status: "Inactive",
  },
  {
    id: 18,
    name: "Elijah Martin",
    role: "Database Administrator",
    email: "elijahmartin@microsoft.com",
    status: "Active",
  },
  {
    id: 19,
    name: "Amelia Young",
    role: "Marketing Specialist",
    email: "ameliayoung@microsoft.com",
    status: "Active",
  },
  {
    id: 20,
    name: "Logan Hill",
    role: "Network Engineer",
    email: "loganhill@microsoft.com",
    status: "Inactive",
  },
  {
    id: 21,
    name: "Harper Walker",
    role: "Machine Learning Engineer",
    email: "harperwalker@microsoft.com",
    status: "Active",
  },
  {
    id: 22,
    name: "Alexander Hall",
    role: "System Analyst",
    email: "alexanderhall@microsoft.com",
    status: "Active",
  },
  {
    id: 23,
    name: "Ella Allen",
    role: "Software Architect",
    email: "ellaallen@microsoft.com",
    status: "Inactive",
  },
  {
    id: 24,
    name: "Henry Scott",
    role: "Tech Support Engineer",
    email: "henryscott@microsoft.com",
    status: "Active",
  },
  {
    id: 25,
    name: "Aria Adams",
    role: "Frontend Engineer",
    email: "ariaadams@microsoft.com",
    status: "Active",
  },
  {
    id: 26,
    name: "Jackson Wright",
    role: "Technical Writer",
    email: "jacksonwright@microsoft.com",
    status: "Active",
  },
  {
    id: 27,
    name: "Scarlett Green",
    role: "Content Strategist",
    email: "scarlettgreen@microsoft.com",
    status: "Active",
  },
  {
    id: 28,
    name: "Daniel Baker",
    role: "IT Manager",
    email: "danielbaker@microsoft.com",
    status: "Inactive",
  },
  {
    id: 29,
    name: "Chloe Rivera",
    role: "Graphic Designer",
    email: "chloerivera@microsoft.com",
    status: "Active",
  },
  {
    id: 30,
    name: "Sebastian Carter",
    role: "Solutions Engineer",
    email: "sebastiancarter@microsoft.com",
    status: "Active",
  },
  {
    id: 31,
    name: "Jackson Roberts",
    role: "Cloud Consultant",
    email: "jacksonroberts@microsoft.com",
    status: "Active",
  },
  {
    id: 32,
    name: "Zoe Mitchell",
    role: "Product Designer",
    email: "zoemitchell@microsoft.com",
    status: "Active",
  },
  {
    id: 33,
    name: "Oliver Clark",
    role: "Web Developer",
    email: "oliverclark@microsoft.com",
    status: "Active",
  },
];

export default employeesData;
